apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ticketing
  template:
    metadata:
      labels:
        app: ticketing
    spec:
      containers:
      - name: ticketing-container
        image: natourcam/ticketing:latest
        ports:
        - containerPort: 3000
